# Generated by Django 5.2.8 on 2025-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_quiz_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='awarded_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
