# Generated by Django 5.2.8 on 2025-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_answer_awarded_points_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/'),
        ),
        migrations.AddField(
            model_name='homework',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited attempts.', null=True),
        ),
    ]
