# Generated by Django 5.2.8 on 2025-12-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_homework_attachment_homework_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework_attachments/'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited attempts'),
        ),
    ]
