# Generated by Django 5.2.8 on 2025-12-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_alter_question_options_alter_question_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lessons/attachments/'),
        ),
    ]
